/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import View=Laya.View;
import Dialog=Laya.Dialog;
import Scene=Laya.Scene;
var REG: Function = Laya.ClassUtils.regClass;
export module ui.game {
    export class GameSceneUI extends View {
		public box_scene3D:Laya.Sprite;
		public box_UI:Laya.Box;
		public lvlLabel:Laya.Label;
		public winLabel:Laya.Label;
		public btn_back:Laya.Image;
		public btn_cannon:Laya.Image;
		public btn_restart:Laya.Image;
		public btn_next:Laya.Image;
		public btn_rewardBullet:Laya.Image;
		public box_tutorial:Laya.Box;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("game/GameScene");
        }
    }
    REG("ui.game.GameSceneUI",GameSceneUI);
}
export module ui.home {
    export class HomeViewUI extends View {
		public mask_homeView:Laya.Image;
		public box_UI:Laya.Box;
		public box_homeIcon:Laya.Box;
		public box_drawer:Laya.Box;
		public box_moreGame:Laya.Box;
		public btn_background:Laya.Image;
		public btn_bullet:Laya.Image;
		public btn_cannon:Laya.Image;
		public btn_sound:Laya.Image;
		public btn_start:Laya.Image;
		public btn_vibration:Laya.Image;
		public label_highScore:Laya.Label;
		public label_level:Laya.Label;
		public icon_gameTitle:Laya.Image;
		public box_cannon:Laya.Box;
		public box_cannonScene3D:Laya.Box;
		public btn_cannonBack:Laya.Image;
		public icon_diamond:Laya.Image;
		public text_diamond:laya.display.Text;
		public box_bannar:Laya.Image;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("home/HomeView");
        }
    }
    REG("ui.home.HomeViewUI",HomeViewUI);
}
export module ui.over {
    export class OverViewUI extends View {
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("over/OverView");
        }
    }
    REG("ui.over.OverViewUI",OverViewUI);
}